Pouvoir créer des listes de structures favorites
betagouv/itou-marche pull request #142
Opened 2021-12-03 10:25 UTC by raphodn

### Quoi ?

- pouvoir ajouter une structures trouvée ) une liste de favoris 
- fonctionnalité réservée aux utilisateurs connectés

2021-12-21 10:53 UTC, raphodn commented
![](https://github.trello.services/images/mini-trello-icon.png) [En tant qu'acheteur, je veux mettre des structures en favoris](https://trello.com/c/OocBJVTQ/497-en-tant-quacheteur-je-veux-mettre-des-structures-en-favoris)

2021-12-28 06:14 UTC, madjid-asa requested changes
Gros boulot 🔥

2021-12-28 07:38 UTC, raphodn commented on lemarche/favorites/migrations/0002_favoriteitem.py
> +                "ordering": ["-created_at"],
je pense que created_at & updated_at seront toujours les mêmes : car les actions possibles sont ajout & suppression. Du coup je voyais ca comme "trier par date d'ajout"

2021-12-28 07:41 UTC, raphodn commented on lemarche/siaes/tests.py
> +    # see favorites > tests.py
bien vu, en fait je test au dessus la queryset `annotate_with_user_favorite_list_count` car je m'en sers dans les template. Mais il faudrait peut-être que je supprime `annotate_with_user_favorite_list_ids` car je ne m'en sers pas

2021-12-28 07:42 UTC, raphodn commented on lemarche/templates/siaes/_card_search_result.html
> +                <a href="{% url 'siae:detail' siae.slug %}" class="text-decoration-none stretched-link">
faut demander à David ^^ Mais c'est la seule solution "html-approved / accessible", il faut mettre un <a> autour des liens

2021-12-28 07:42 UTC, raphodn commented on lemarche/templates/siaes/_card_search_result.html
> +                        <a href="#" id="favorite-modal-btn" class="btn btn-favorite">
ok !

2021-12-28 07:46 UTC, raphodn commented on lemarche/templates/siaes/_card_search_result.html
> +                        <a href="#" id="favorite-modal-btn" class="btn btn-favorite">
Je ferais les modifs dans la PR 3/3. Voire une autre dédiée cette semaine ?

2021-12-28 07:49 UTC, raphodn commented on lemarche/siaes/tests.py
> +    # see favorites > tests.py
j'ai ajouté des tests - ca devrait réparer le CI - https://github.com/betagouv/itou-marche/pull/142/commits/c3b7eeb4c2da38d39fce8b93af00e3000c06a6fa

2021-12-28 12:42 UTC, merged