Dépôt de besoin : formulaire : cleanup
betagouv/itou-marche pull request #553
Opened 2022-12-07 14:26 UTC by raphodn

### Quoi ?

Suite de https://github.com/betagouv/itou-marche/pull/552

J'en un peu homogénéisé le rendu du formulaire : 
- généraliser `row` + `col-12 col-lg-8`
- en règle général pas besoin de `form_group_class`, car `form-group` est ajouté par défaut, et `form-group-required` est ajouté si le champ est required (cf `config/settings/base.py`)

2022-12-07 16:57 UTC, madjid-asa requested changes

2022-12-07 16:57 UTC, madjid-asa commented on lemarche/templates/tenders/create_step_contact.html
> -<div id="serveyTender" class="row">
on a besoin de cet id, il est utilisé au moins pour le css

2022-12-07 17:40 UTC, raphodn commented on lemarche/templates/tenders/create_step_contact.html
> -<div id="serveyTender" class="row">
yes il est utilisé dans `create_step_survey` pour mettre les réponses à plat.
mais dans les autres steps les choix sont multiple & verticaux, non ?

2022-12-08 09:14 UTC, raphodn commented on lemarche/templates/tenders/create_step_contact.html
> -<div id="serveyTender" class="row">
|Avant|Après|
|---|---|
|![Screenshot from 2022-12-08 10-11-02](https://user-images.githubusercontent.com/7147385/206406089-7399c300-0edb-4096-be6d-5dfa9ee1e3dd.png)|![Screenshot from 2022-12-08 10-14-04](https://user-images.githubusercontent.com/7147385/206406407-4b746829-66b1-4580-a8bf-58eb384ccb55.png)|

2022-12-08 11:55 UTC, madjid-asa commented on lemarche/templates/tenders/create_step_contact.html
> -<div id="serveyTender" class="row">
ah meme dans step_contact on les veux horizontaux pour qu'il prenne moins de place :)

2022-12-12 10:40 UTC, raphodn commented on lemarche/templates/tenders/create_step_contact.html
> -<div id="serveyTender" class="row">
on les met à plat partout alors ? sur la première page : "type de besoin" et "type de prestation(s)" sont verticaux

2022-12-15 11:55 UTC, hellodeloo reviewed
Et aussi le stepper et la partie avec les buttons doivent être dans un `col-12 col-lg-7`.
Tell me si tu as besoin d'aide ou que tu préfères que je le fasse

2022-12-15 11:55 UTC, hellodeloo commented on lemarche/templates/tenders/create_step_contact.html
> +<div class="row mb-3 mb-lg-5">
Pas besoin de ces margin `mb-3 mb-lg-5` en plus sur les row.

2022-12-15 11:55 UTC, hellodeloo commented on lemarche/templates/tenders/create_step_contact.html
>      <div class="col-12 col-lg-8">
C'est `col-12 col-lg-7` en fait

2022-12-15 11:55 UTC, hellodeloo commented on lemarche/templates/tenders/create_step_description.html
>          <div class="alert alert-info mt-3 mt-lg-0" role="alert">
Le `role="alert"` n'est qu'a utilisé qu'en cas d'info bloquante importante et dans un état nouveau, pas au chargement de la page (erreur, déconnexion, etc). Sinon plutôt utiliser role="status" mais dans ce cas, pas de role c'est encore mieux

2022-12-15 11:55 UTC, hellodeloo commented on lemarche/templates/tenders/create_step_description.html
>      <div class="col-12 col-lg-4">
`col-12 col-lg-5` du coup

2022-12-15 11:55 UTC, hellodeloo commented on lemarche/templates/tenders/create_step_description.html
>          <div class="alert alert-info mt-3 mt-lg-0" role="alert">
Et en fait, c'est plutot a mettre dans un `.c-form-conseil`. Avec un `data-target-conseil=uniqueID` sur l'input concerné et un `div#uniqueID.is-openable` a l'intérieur du `.c-form-conseil`
Exemple ici  https://betagouv.github.io/itou-theme/layout-itou-form.html

2023-01-14 12:21 UTC, raphodn commented
La plupart des modifs ont été faites dans la PR https://github.com/betagouv/itou-marche/pull/614

2023-01-14 12:21 UTC, closed without merging