Dépendances : mettre à jour le repo pointant vers raphodn
betagouv/itou-marche pull request #860
Opened 2023-08-08 10:21 UTC by raphodn

### Quoi ?

- pyproject : ajout de `.git` dans l'url du repo pointant vers le fork #823
- pre-commit : mise à jour

2023-08-08 10:22 UTC, raphodn commented on poetry.lock
> +files = [
y'a plein de `files = [` qui ont été rajoutés :thinking: 
peut-être lié à ma nouvelle version de poetry ? 1.5.1

2023-08-08 11:53 UTC, SebastienReuiller requested changes
Je pense que l'ajout des `files` n'est pas problématique, mais je suis moins serein sur la suppression de `category`.

2023-08-08 12:21 UTC, raphodn commented on poetry.lock
> -category = "main"
https://python-poetry.org/docs/managing-dependencies/#dependency-groups

> The dependencies declared in tool.poetry.dependencies are part of an implicit main group.

2023-08-08 12:22 UTC, raphodn commented on poetry.lock
> -category = "main"
> The proper way to define a dev dependencies group since Poetry 1.2.0 is the following:

```
[tool.poetry.group.dev.dependencies]
```

> Poetry will slowly transition away from the dev-dependencies notation which will soon be deprecated, so it’s advised to migrate your existing development dependencies to the new group notation.

2023-08-09 07:54 UTC, SebastienReuiller commented on poetry.lock
> -category = "main"
Cool, merci pour les infos !

2023-08-09 08:13 UTC, merged