Dépôt de besoin : utiliser django-sesame pour générer les liens du sondage J+30
betagouv/itou-marche pull request #880
Opened 2023-08-24 17:43 UTC by raphodn

v2 de https://github.com/betagouv/itou-marche/pull/873

### Quoi ?

Grâce à [django-sesame](https://django-sesame.readthedocs.io/en/stable/index.html), les liens envoyés pour le sondage J+30 contiennent un moyen d'authentifier l'utilisateur, même si il n'est pas effectivement connecté à l'application.

Le token généré permet d'authentifier l'utilisateur seulement sur cette page, grâce au nouveau mixin `SesameTenderAuthorRequiredMixin`

2023-08-28 14:21 UTC, SebastienReuiller commented on lemarche/www/tenders/tasks.py
> +            user_sesame_query_string = sesame_get_query_string(tender.author)
Tu ne passes pas de scope ici ?

2023-08-29 07:37 UTC, SebastienReuiller requested changes
Juste un petit test pour être serein sur le fait que le `token` n'authentifie pas pour de bon.

2023-08-29 07:37 UTC, SebastienReuiller commented on lemarche/www/tenders/tests.py
> +        self.assertContains(response, "Merci pour vote réponse")
Si le `token` même sans `scope` n'authentifie pas sur tout le site, je pense qu'il faudrait le tester ici en naviguant sur une page protégée.

2023-08-29 09:54 UTC, raphodn commented on lemarche/www/tenders/tests.py
> +        self.assertContains(response, "Merci pour vote réponse")
t'as raison, j'ai rajouté un test supplémentaire :pray: 
https://github.com/betagouv/itou-marche/pull/880/commits/22d6596d4a41268065f4da0ad066df43dd28e47f

2023-08-29 10:11 UTC, merged