Mise à jours de la date de dernière activité des structures
betagouv/itou-marche pull request #930
Opened 2023-10-02 10:45 UTC by madjid-asa

### Quoi ?

Mise à jours de la date de dernière activité des structures.

### Pourquoi ?

Pour avoir des dates plus récentes sur l'activité des structures.

2023-10-03 09:14 UTC, raphodn commented on lemarche/siaes/models.py
> +            users_last_activities = self.users.values_list(
il y a moyen d'utiliser `Greatest` pour simplifier tout ca ? :sweat_smile: 

https://stackoverflow.com/a/46211741/4293684

2023-10-03 09:46 UTC, raphodn commented on lemarche/siaes/models.py
> +            users_last_activities = self.users.values_list(
déjà utilisé dans `Tender.with_siae_stats()`

2023-10-09 07:57 UTC, madjid-asa commented on lemarche/siaes/models.py
> +            users_last_activities = self.users.values_list(
done

2023-10-16 08:52 UTC, SebastienReuiller requested changes
Top ! 👏 Par contre, je pense que ça mériterait des tests 😉

2023-10-17 12:41 UTC, madjid-asa commented
> Top ! 👏 Par contre, je pense que ça mériterait des tests 😉

Done

2023-10-18 08:01 UTC, SebastienReuiller commented on lemarche/siaes/tests.py
> +        # cls.users = [UserFactory() for i in range(3)]
Un petit commentaire qui est resté là.

2023-10-25 14:03 UTC, merged